# -*- coding: utf-8 -*-
"""
  Author: Author
  Email : liusuri@mail.dlut.edu.cn
   Time : 2025/7/25 10:40
Function: 1) Compare the KPIs under different theta
          2) when *dist_time_info.xlsx under different \theta is generated by build_tables_6_7_case_study.py, this .py file aggregates the results together
"""

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
folder = ROOT / 'output'

df_theta_compare = pd.DataFrame()

for theta_in_file in [0.0001, 0.002, 0.005]:
    matches = sorted(folder.glob(
        '*-theta_{}opt_solution_info_Delta_5dist_time_info.xlsx'.format(theta_in_file)
    ))
    if len(matches) != 1:
        raise FileNotFoundError(
            'Expected one Tables 6-7 workbook for theta={}, found {}. '
            'Run build_tables_6_7_case_study.py first.'.format(theta_in_file, len(matches))
        )
    result_file = matches[0]
    df = pd.read_excel(result_file, sheet_name='obj_info')
    # df = df[df['transport_mode'].isin(['all', 'shuttle', 'shuttle+bus'])]
    df = df[df['transport_mode']=='all']
    df['theta'] = [theta_in_file] * 4
    df = df[['theta', 'solution_type', 'income', 'transport_mode', 'n_trips', 'n_amount', 'model_distance', 'direct_distance', 'model_travel_time', 'direct_travel_time']]
    df_theta_compare = pd.concat([df_theta_compare, df])

out_file = folder / 'theta_compare.xlsx'
df_theta_compare.to_excel(out_file, index=False)



